// Smart Market — shared design tokens & style objects
export const colors = {
  darkGreen: '#1a4d24',
  midGreen: '#3b7a45',
  lightGreen: '#7ab87f',
  paleGreen: '#a8d8a8',
  bgGreen: '#e8f5e3',
  borderGreen: '#c8dfc0',
  softBorder: '#ddeedd',
  pageBg: '#f7f9f5',
  cardBg: '#fff',
  textDark: '#1a3d22',
  textMid: '#3b7a45',
  textLight: '#7ab87f',
  textPale: '#9ab89a',
};

export const s = {
  phone: {
    width: '100%',
    background: colors.pageBg,
    borderRadius: 20,
    overflow: 'hidden',
    border: `1.5px solid ${colors.borderGreen}`,
    fontFamily: 'system-ui, sans-serif',
  },
  topbar: {
    background: colors.darkGreen,
    padding: '11px 14px 9px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tbTitle: { fontSize: 15, fontWeight: 500, color: '#e8f5e3' },
  tbSub: { fontSize: 11, color: colors.lightGreen },
  body: { background: colors.pageBg, padding: '11px 12px' },
  searchBar: {
    background: '#fff',
    border: `1px solid ${colors.borderGreen}`,
    borderRadius: 10,
    padding: '7px 11px',
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    marginBottom: 9,
  },
  chip: {
    background: '#fff',
    color: colors.midGreen,
    border: `1px solid #b8d8b0`,
    borderRadius: 20,
    padding: '3px 10px',
    fontSize: 11,
    cursor: 'pointer',
  },
  chipOn: {
    background: colors.darkGreen,
    color: '#e8f5e3',
    borderColor: colors.darkGreen,
    borderRadius: 20,
    padding: '3px 10px',
    fontSize: 11,
  },
  pcard: {
    background: '#fff',
    border: `1px solid ${colors.softBorder}`,
    borderRadius: 10,
    overflow: 'hidden',
  },
  pimg: {
    background: '#eef5ec',
    height: 58,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinfo: { padding: '6px 7px' },
  pname: {
    fontSize: 11,
    fontWeight: 500,
    color: colors.textDark,
    marginBottom: 3,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  pprice: { fontSize: 13, fontWeight: 500, color: colors.darkGreen },
  ppriceSub: { fontSize: 10, color: colors.lightGreen },
  greenBtn: {
    background: colors.darkGreen,
    color: '#e8f5e3',
    borderRadius: 10,
    padding: '9px 14px',
    fontSize: 13,
    fontWeight: 500,
    textAlign: 'center',
    marginBottom: 7,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    cursor: 'pointer',
    border: 'none',
    width: '100%',
  },
  outlineBtn: {
    border: `1px solid #b8d8b0`,
    color: colors.darkGreen,
    borderRadius: 10,
    padding: '9px 14px',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 7,
    background: '#fff',
    cursor: 'pointer',
    width: '100%',
    display: 'block',
  },
  bnav: {
    background: '#fff',
    borderTop: `1px solid ${colors.borderGreen}`,
    display: 'flex',
    justifyContent: 'space-around',
    padding: '7px 0 5px',
  },
  navItem: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 2 },
  navLabel: { fontSize: 9, color: colors.textPale },
  navLabelOn: { fontSize: 9, color: colors.darkGreen },
  bcard: {
    background: '#fff',
    border: `1px solid ${colors.softBorder}`,
    borderRadius: 10,
    padding: '9px 11px',
    marginBottom: 7,
  },
  bcTitle: { fontSize: 13, fontWeight: 500, color: colors.textDark, marginBottom: 5 },
  qbtn: {
    background: colors.bgGreen,
    color: colors.darkGreen,
    borderRadius: 5,
    width: 20,
    height: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    border: 'none',
    cursor: 'pointer',
  },
  totalBar: {
    background: colors.bgGreen,
    borderRadius: 9,
    padding: '9px 13px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: '8px 0',
  },
};

export const storeBadgeStyle = (store) => {
  const map = {
    A101: { background: '#fff3e0', color: '#e65100' },
    BIM: { background: '#e3f2fd', color: '#0d47a1' },
    SOK: { background: '#fce4ec', color: '#880e4f' },
    MIGROS: { background: '#f3e5f5', color: '#4a148c' },
    CF: { background: '#e8f5e9', color: '#1b5e20' },
  };
  return {
    ...(map[store] || map.CF),
    display: 'inline-block',
    fontSize: 9,
    padding: '2px 5px',
    borderRadius: 4,
    marginTop: 3,
  };
};
